blank_issues_enabled: true
contact_links:
  - name: ğŸ“ í…œí”Œë¦¿ ì‚¬ìš©ë°©ë²•
    url: https://docs.google.com/document/d/18pA3u8Mog-qbhOKdeeLN2OoSpXw_bfgNqMqn8WW-dLk/edit?usp=drive_link
    about: ì´ìŠˆ í…œí”Œë¦¿ ì‘ì„±/ì‚¬ìš© ê°€ì´ë“œëŠ” ì—¬ê¸°ì„œ í™•ì¸í•˜ì„¸ìš”.
